<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <AssemblyName>HashForge</AssemblyName>
    <RootNamespace>HashForge</RootNamespace>
    <Authors>William Tritapepe</Authors>
    <Company>William Tritapepe</Company>
    <Copyright>Copyright © 2025 William Tritapepe</Copyright>
    <Version>1.0.0</Version>
    <Description>Utility per calcolo e validazione di hash (MD5, SHA, ecc.).</Description>
    <!-- keep custom output paths if desired -->
    <BaseOutputPath>..\Artifacts\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>..\Artifacts\obj\</BaseIntermediateOutputPath>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <ItemGroup>
    <None Include="icon.ico" />
    <None Include="icon.png" />
  </ItemGroup>

</Project>
